name: Deploy Infrastructure with Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6
        
      - name: Initialize Terraform
        run: terraform init
        
      - name: Validate Terraform
        run: terraform validate
        
      - name: Apply Terraform
        run: terraform apply -auto-approve
        
      - name: Upload Terraform state to S3 (Optional)
        run: |
          terraform state push s3://aftab-is-pheonix/environment/terraform.tfstate
        
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Ansible and Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible
          pip install boto3 botocore
        
      - name: Copy SSH Key to Bastion Host
        run: |
          scp -i my_key my_key ec2-user@${{ secrets.BASTION_IP }}:/home/ec2-user/
        
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory/aws_ec2.yaml webserver_setup.yaml -u ec2-user --private-key ~/.ssh/my_key
        
  validation:
    runs-on: ubuntu-latest
    needs: ansible
    
    steps:
      - name: Validate ALB
        run: |
          curl http://${{ needs.terraform.outputs.alb_dns_name }}
        
      - name: Validate Web Servers (VM3 & VM4)
        run: |
          curl http://${{ needs.terraform.outputs.vm3_public_ip }}
          curl http://${{ needs.terraform.outputs.vm4_public_ip }}
